[pytest]
# Кажемо pytest, де шукати тести за замовчуванням
testpaths = tests

# Базові налаштування (завжди генерувати трасування при падінні та запускати у headed/headless залежно від потреб)
addopts = --browser chromium --tracing=retain-on-failure

# Шаблони для пошуку тестів
python_files = test_*.py
python_functions = test_*